name: build-and-release
run-name: Blobs build (and release if version tag)

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        arch: [ARM64, X64]
    name: build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install nix
        uses: cachix/install-nix-action@v20
      - name: build artifacts
        run: |
          case "${{ matrix.arch }}" in
            X64)
              nix-build --pure -A all
              ;;
            ARM64)
              nix-build -A all --arg pkgs '(import ./nixpkgs.nix { }).pkgsCross.aarch64-multiplatform'
              ;;
          esac
      - name: upload architecture tarball
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.arch }}
          path: ./result/*

  release:
    # Only trigger releases on version tags
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download all artifacts
        uses: actions/download-artifact@v7
        with:
          path: ${{ github.workspace }}/enclaves-blobs/
      - name: Prepare release
        run: |
          mkdir -p ${{ github.workspace }}/release
          cd ${{ github.workspace }}/enclaves-blobs/build-X64/x86_64
          for f in $(ls); do ( mv $f ${{ github.workspace }}/release/$f-amd64 ); done
          cd ${{ github.workspace }}/enclaves-blobs/build-ARM64/aarch64
          for f in $(ls); do ( mv $f ${{ github.workspace }}/release/$f-arm64 ); done
      - name: Release Information
        run: |
          cd ${{ github.workspace }}/release
          echo "Current build URL: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          echo "The full commit hash is ${{ github.sha }}"
          echo "Release files with SHA256 checksums:"
          sha256sum *
      - name: Release
        uses: softprops/action-gh-release@v2
        id: create_release
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          make_latest: true
          files: release/*
        env:
          GITHUB_TOKEN: ${{ github.token }}
